<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-5TFUKJL1" failures="0" tests="5" name="com.nexttechITC.TestRunner.TestNGTestRunner$TestRunner" time="30.204" errors="1" timestamp="16 May 2022 22:49:24 GMT" skipped="0">
  <testcase classname="com.nexttechITC.TestRunner.TestNGTestRunner$TestRunner" name="runScenario" time="7.034">
    <error message="Step [user enter {string} and&quot;Bari&quot; and valid {string} and {string}] is defined with 4 parameters at &#039;com.nexttechITC.Stepdefs.FacebookSignup.user_enter_and_bari_and_valid_and(java.lang.String,java.lang.String,java.lang.String,java.lang.String)&#039;.
However, the gherkin step has 3 arguments:
 * &quot;Amy&quot;
 * &quot;esdy@gmail.com&quot;
 * &quot;class@2020&quot;
Step text: user enter &quot;Amy&quot; and&quot;Bari&quot; and valid &quot;esdy@gmail.com&quot; and &quot;class@2020&quot;" type="io.cucumber.core.exception.CucumberException">
      <![CDATA[io.cucumber.core.exception.CucumberException: Step [user enter {string} and"Bari" and valid {string} and {string}] is defined with 4 parameters at 'com.nexttechITC.Stepdefs.FacebookSignup.user_enter_and_bari_and_valid_and(java.lang.String,java.lang.String,java.lang.String,java.lang.String)'.
However, the gherkin step has 3 arguments:
 * "Amy"
 * "esdy@gmail.com"
 * "class@2020"
Step text: user enter "Amy" and"Bari" and valid "esdy@gmail.com" and "class@2020"
	at io.cucumber.core.runner.PickleStepDefinitionMatch.arityMismatch(PickleStepDefinitionMatch.java:83)
	at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:42)
	at io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
	at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:86)
	at io.cucumber.core.runner.TestStep.run(TestStep.java:57)
	at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:51)
	at io.cucumber.core.runner.TestCase.run(TestCase.java:95)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:75)
	at io.cucumber.testng.TestNGCucumberRunner.lambda$runScenario$1(TestNGCucumberRunner.java:132)
	at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$3(CucumberExecutionContext.java:110)
	at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
	at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:110)
	at io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:129)
	at io.cucumber.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:35)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <testcase classname="com.nexttechITC.TestRunner.TestNGTestRunner$TestRunner" name="runScenario" time="5.389"/>
  <testcase classname="com.nexttechITC.TestRunner.TestNGTestRunner$TestRunner" name="runScenario" time="6.440"/>
  <testcase classname="com.nexttechITC.TestRunner.TestNGTestRunner$TestRunner" name="runScenario" time="4.385"/>
  <testcase classname="com.nexttechITC.TestRunner.TestNGTestRunner$TestRunner" name="runScenario" time="6.956"/>
</testsuite> <!-- com.nexttechITC.TestRunner.TestNGTestRunner$TestRunner -->
